name: trips-CI
on:
  pull_request:
    branches:
    - master
    - ch3
    paths:
    - apis/trips/**
    - .github/workflows/trips-CI.yml
  
  push:
    branches:
    - master
    - ch3
    paths:
    - apis/trips/**
    - .github/workflows/trips-CI.yml
    
defaults:
  run:
    working-directory: apis/trips
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT CURRENT REPO
      uses: actions/checkout@v2

    - name: Setup Go 1.x
      uses: actions/setup-go@v2

    - name: Build go
      run: go build -v

    - name: Test
      run: go test -v ./tests/ .
