name: POI-CI
on:
  pull_request:
    branches:
    - master
    - ch3
    paths:
    - apis/user-java/**
    - .github/workflows/user-java-CI.yml
  
  push:
    branches:
    - master
    - ch3
    paths:
    - apis/user-java/**
    - .github/workflows/user-java-CI.yml
    
defaults:
  run:
    working-directory: apis/user-java/
    
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: CHECKOUT CURRENT REPO
      uses: actions/checkout@v2

    - name: Setup JDK 1.8 
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: FailureScript
      uses: actions/github-script@v4
      if: failure()
      with:
        script: |
          let body = "${{ env.build_name }} Worflow Failure \n ";            
          body += "Build Number: ${{ github.run_number }} \n";            
          body += "Build Log: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} \n";            
          body += "SHA: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})\n";            
          await github.issues.create({            
          owner: context.repo.owner,            
          repo: context.repo.repo,            
          title: "${{ env.build_name }} Workflow ${{ github.run_number }} Failed! ",            
          body: body            
          });
